<?php

declare(strict_types=1);

return [
    'roles' => [
        'super_admin' => [
            'label' => 'Super Admin',
            'permissions' => ['*'],
        ],
    ],
    'permissions' => [
        'customers.view_list',
        'customers.search',
        'customers.view_detail',
        'customers.view_submitted_data',
        'customers.create',
        'customers.edit',
        'customers.delete',
        'customers.view_payment_amount',
        'customers.export',
        'products.view',
        'products.create',
        'products.edit',
        'products.delete',
        'products.manage_fields',
        'products.manage_partner_access',
        'partners.view',
        'partners.create',
        'partners.edit',
        'partners.delete',
        'partners.view_api_usage',
        'dashboard.customer_overview',
        'dashboard.metrics_overview',
        'dashboard.platform_overview',
        'reports.customer_summary',
        'reports.customer_acquisition',
        'reports.revenue_by_product',
        'reports.partner_performance',
        'reports.view',
        'reports.export',
        'reports.export_csv',
        'reports.export_excel',
        'reports.export_pdf',
        'reports.scheduled_reports',
        'users.view',
        'users.create',
        'users.edit',
        'users.deactivate',
        'users.assign_roles',
        'audit_logs.view',
        'settings.system',
        'settings.email',
    ],
    'modules' => [
        'super_admin' => ['dashboard', 'customers', 'products', 'partners', 'users', 'reports', 'audit_logs', 'settings'],
    ],
];
